### ISSUE TITLE
cannot build partition with pinv parameters other than 0 or 1

### ISSUE THREAD

**Issue by rLannes** [sjspielman/pyvolve#12]
hi,
It seems impossible to add invariant sites in partitions. It only accept value of 1 or 0 for "pinv" parameter

It return this error:
Traceback (most recent call last):
  File "/home/disque3To/Romain/Projet/simulation_tree/src/scripts/make_simulation.py", line 113, in <module>
    partition = get_partition(alpha=alpha, prot_size=prot_size, inv=inv)
  File "/home/disque3To/Romain/Projet/simulation_tree/src/scripts/make_simulation.py", line 29, in get_partition
    my_partition = pyvolve.Partition(models=aa_model, size=prot_size)
  File "/usr/local/lib/python3.5/dist-packages/pyvolve/partition.py", line 53, in __init__
    self._divvy_partition_size()
  File "/usr/local/lib/python3.5/dist-packages/pyvolve/partition.py", line 120, in _divvy_partition_size
    rate_occurrences = np.random.choice(nc, int(self.size), p = self._root_model.rate_probs)          
  File "mtrand.pyx", line 1146, in mtrand.RandomState.choice
ValueError: probabilities do not sum to 1

To test it, I have this function to make a partition.
```

import pyvolve
def get_partition(alpha, prot_size, inv, num_cat=4):

	aa_model = pyvolve.Model("LG", alpha=alpha, num_categories=num_cat, pinv=inv)
	my_partition = pyvolve.Partition(models=aa_model, size=prot_size)
	return my_partition

aa = get_partition(alpha=1.243, prot_size=300, num_cat=4, inv=0311284046692607)  # Error
aa = get_partition(alpha=1.243, prot_size=300, num_cat=4, inv=0)  # Works
```

I don't understand what happens, my parameters come for a real tree. 
I am using python3.5.

**Comment by sjspielman** [comment]
Hi @rLannes, 

This was indeed a bug with +G+I model specification. Please update to the new release `0.8.9` (available here or via `pip`). This should address your problem, and please re-open this issue if the same problem recurs for you.

Best, 
Stephanie
