### ISSUE TITLE
Bio package Align can't import?

### ISSUE THREAD

**Issue by markkessler66** [sjspielman/pyvolve#17]
Traceback (most recent call last):
  File "c:\Users\markk\OneDrive\Documents\Summer_Research_2020\OurNet\PhyNet.py", line 13, in <module>
    import pyvolve
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\pyvolve\__init__.py", line 29, in <module>
    from .model import *
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\pyvolve\model.py", line 16, in <module>
    from .matrix_builder import *
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\pyvolve\matrix_builder.py", line 22, in <module>
    from .state_freqs import *
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\pyvolve\state_freqs.py", line 20, in <module>
    from Bio import SeqIO, AlignIO
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\Bio\SeqIO\__init__.py", line 382, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\Bio\Align\__init__.py", line 21, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners' from 'Bio.Align' (C:\Users\markk\Anaconda3\lib\site-packages\IPython\extensions\Bio\Align\__init__.py)

**Comment by sjspielman** [comment]
Hi @markkessler66 , 

This is almost certainly not a bug with pyvolve, and most likely has to do with how you have installed Biopython in the conda environment. 

Without seeing your entire system setup and any commands issued, including code, that gave rise to this portion of an error message, I can't offer any further advice. I have relatively little experience using conda as well as I use Mac and/or Linux, so you might want to ask someone with more knowledge of this management system.

Best, 
Stephanie
